const stations = [
  "Churchgate",
  "Marine Lines",
  "Charni Road",
  "Grant Road",
  "Mumbai Central",
  "Mahalaxmi",
  "Lower Parel",
  "Prabhadevi",
  "Dadar",
  "Matunga Road",
  "Mahim Junction",
  "Bandra",
  "Khar Road",
  "Santacruz",
  "Vile Parle",
  "Andheri",
  "Jogeshwari",
  "Goregaon",
  "Malad",
  "Kandivali",
  "Borivali",
  "Dahisar",
  "Mira Road",
  "Bhayandar",
  "Naigaon",
  "Vasai Road",
  "Nalasopara",
  "Virar",

  "Chhatrapati Shivaji Maharaj Terminus",
  "Masjid",
  "Sandhurst Road",
  "Byculla",
  "Chinchpokli",
  "Currey Road",
  "Parel",
  "Dadar",
  "Matunga",
  "Sion",
  "Kurla",
  "Vidyavihar",
  "Ghatkopar",
  "Vikhroli",
  "Kanjurmarg",
  "Bhandup",
  "Nahur",
  "Mulund",
  "Thane",
  "Kalwa",
  "Mumbra",
  "Diva",
  "Kopar",
  "Dombivli",
  "Thakurli",
  "Kalyan",

  "Wadala Road",
  "Guru Tegh Bahadur Nagar",
  "Chunabhatti",
  "Kurla",
  "Tilak Nagar",
  "Chembur",
  "Govandi",
  "Mankhurd",
  "Vashi",
  "Sanpada",
  "Juinagar",
  "Nerul",
  "Seawoods-Darave",
  "Belapur CBD",
  "Kharghar",
  "Mansarovar",
  "Khandeshwar",
  "Panvel",

  "Airoli",
  "Rabale",
  "Ghansoli",
  "Koparkhairane",
  "Turbhe",

  "Dockyard Road",
  "Reay Road",
  "Cotton Green",
  "Sewri",
  "Wadala Road",
  "King's Circle",

  "Lokmanya Tilak Terminus"
];

export default stations;